import "./globals.css";
import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";

import { AuthProvider } from "@/context/auth-context";

const font = Work_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Lodge - Your Perfect Stay Awaits",
  description: "Generated by create next app",
  keywords:
    "accommodations, booking, travel, rentals, experiences, vacation, lodge",
  authors: [{ name: "Hilthon", url: "https://tandt-timothy.vercel.app" }],
  openGraph: {
    title: "Lodge - Your Perfect Stay Awaits",
    description:
      "Find and book unique accommodations and experiences with Lodge, your travel companion for unforgettable stays.",
    url: "https://www.lodge.com",
    type: "website",
  },
  viewport: "width=device-width, initial-scale=1",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
