import "./globals.css";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";

import { AuthProvider } from "@/context/auth-context";
import { ToastProvider } from "@/providers/toast-provider";
import { QueryProvider } from "@/providers/query-provider";
import { ModalProvider } from "@/providers/modal-provider";

const font = Nunito({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Lodge - Your Perfect Stay Awaits",
  description: "Generated by create next app",
  keywords:
    "accommodations, booking, travel, rentals, experiences, vacation, lodge",
  authors: [{ name: "Hilthon", url: "https://tandt-timothy.vercel.app" }],
  openGraph: {
    title: "Lodge - Your Perfect Stay Awaits",
    description:
      "Find and book unique accommodations and experiences with Lodge, your travel companion for unforgettable stays.",
    url: "https://www.lodge.com",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <QueryProvider>
          <AuthProvider>
            <ToastProvider />
            <ModalProvider />
            {children}
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
